### ISSUE TITLE
fix: 동행글 생성 시 값이 전달되지 않는 문제

### ISSUE THREAD

**Issue by vmkmym** [dnd-side-project/dnd-11th-1-android#26]
### 문제 요약
[StateFlow의 값이 BoardRequestDto객체에 할당 되지 않는 문제](https://gist.github.com/vmkmym/d5d12fbeda0f180b88042717a0a47cde)

### 시도해 본 방법
- [값 직접 할당](https://inblog.ai/code-with-me/android-viewmodel%EC%97%90%EC%84%9C-%EC%82%AC%EC%9A%A9%EC%9E%90%EA%B0%80-%EC%9E%85%EB%A0%A5%ED%95%9C-%EA%B0%92%EB%93%A4%EC%9D%B4-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EB%B0%98%EC%98%81%EB%90%98%EC%A7%80-%EC%95%8A%EC%95%84-%ED%95%84%EC%9A%94%ED%95%9C-%EC%A0%95%EB%B3%B4%EA%B0%80-%EB%88%84%EB%9D%BD%EB%90%98%EB%8A%94-%EB%AC%B8%EC%A0%9C-30277?traffic_type=internal)
- 오픈채팅방에서 물어보니까 launchIn 스코프 범위를 정해보라는 조언 -> 함수 호출 이후에 값 변경 할 경우가 없어서 범위를 정할 이유가 없다는 llm답변 or 이 부분이 값 직접 할당 안되는 문제와는 별개라는 답변으로 pass
- top bar에서 미리 선언해서 값 전달이 초기값으로만 전달된다면 -> 더 알아봐야 함..
- (new) createPost 함수 내에서 formState가 불변성을 유지하고 있지 않음 -> 중간에서 값이 초기화가 됨 

### 원인
currentFormState의 값이 제대로 반영되었더라도, BoardRequestDto로 전달될 때 값이 초기화되는 원인은 formState가 불변 객체이거나 StateFlow 업데이트 시점을 잘못 처리했을 가능성이 큽니다. 이를 해결하기 위해 formState가 불변성을 유지하고 있거나, 깊은 복사를 통해 정확한 상태를 전달하는지 확인해보세요.
- 깊은 복사를 통해 확인 시 불변성 유지 못하고 값이 초기화 됨.
```
val currentFormState = formState.value
Log.d("PostBoardViewModel", "Current form state: $currentFormState")
// logcat
Form state updated: BoardFormState(title=123456, content=67890, ...)
Current form state: BoardFormState(title=, content=, ...)
```
- StateFlow 또는 MutableStateFlow의 상태 관리 과정에서 불변성을 제대로 유지하지 못하거나, 상태가 제대로 업데이트되지 않고 초기화되는 문제일 가능성

### 해결 방안
```Kotlin
private fun updateField(update: (BoardFormState) -> BoardFormState) {
        _formState.update(update)
        Log.d("PostBoardViewModel", "_formState.value: ${_formState.value}")
        Log.d("PostBoardViewModel", "formState.value: ${formState.value}")

        val currentFormState = formState.value
        val boardRequest = BoardRequestDto(
            title = currentFormState.title,
            content = currentFormState.content,
            preferredGender = currentFormState.preferredGender,
            preferredAge = currentFormState.preferredAge,
            tagNames = currentFormState.tagNames,
            categories = currentFormState.category,
            region = currentFormState.region,
            startDate = currentFormState.startDate,
            endDate = currentFormState.endDate,
            capacity = currentFormState.capacity,
            imageUrls = currentFormState.imageUris,
            boardStatus = currentFormState.boardStatus
        )
        Log.d("PostBoardViewModel", "updateField DTO created: $boardRequest")
    }
```
- 여기서는 Dto 객체에 값이 할당됨. (뷰모델 스코프 내에서 할당이 안되는 이유는 뭘까)

1. 전역상태로 `boradRequestDto` 관리
```Kotlin
private var boardRequest: BoardRequestDto? = null

private fun updateField(update: (BoardFormState) -> BoardFormState) {
    _formState.update(update)
    Log.d("PostBoardViewModel", "_formState.value: ${_formState.value}")
    Log.d("PostBoardViewModel", "formState.value: ${formState.value}")

    val currentFormState = formState.value
    boardRequest = BoardRequestDto(
        title = currentFormState.title,
        content = currentFormState.content,
        preferredGender = currentFormState.preferredGender,
        preferredAge = currentFormState.preferredAge,
        tagNames = currentFormState.tagNames,
        categories = currentFormState.category,
        region = currentFormState.region,
        startDate = currentFormState.startDate,
        endDate = currentFormState.endDate,
        capacity = currentFormState.capacity,
        imageUrls = currentFormState.imageUris,
        boardStatus = currentFormState.boardStatus
    )
    Log.d("PostBoardViewModel", "updateField DTO created: $boardRequest")
}

fun createPost() {
    viewModelScope.launch {
        _uiState.value = PostBoardUiState.Loading

        boardRequest?.let {
            try {
                val result = boardRepository.postBoard(it)
                // Post 처리 로직...
            } catch (e: Exception) {
                _uiState.value = PostBoardUiState.Error("네트워크 오류: ${e.message}")
            }
        } ?: run {
            _uiState.value = PostBoardUiState.Error("BoardRequestDto가 생성되지 않았습니다.")
        }
    }
}

```

2. ViewModelScope 차이
- hiltViewModel()을 사용하여 ViewModel을 선언했음에도 불구하고 상태가 유지되지 않는다면, 새로운 PostBoardViewModel 인스턴스가 생성되고 있는 이유는 모듈 간에서 ViewModel 인스턴스가 제대로 공유되지 않기 때문일 수 있습니다.
- 현재 **메인 액티비티(앱 모듈)**와 **동행글 생성 화면(홈 모듈)**이 서로 다른 모듈에 있기 때문에 ViewModel 인스턴스를 제대로 공유하지 못하는 문제가 발생할 수 있습니다.

**Comment by uselessnaming** [comment]
개인적인 생각이지만 MainActivity에서 선언된 게시글 작성에 사용되는 view model에서 toBoardRequestDto()를 할 때 가져오는 값들과 게시글 작성 화면에서의 view model이 별개로 동작하고 있는 것이 아닐까 생각이 듭니당

**Comment by vmkmym** [comment]
혹시 잘못 선언했나 싶어서 확인했는데 두 곳에서 뷰모델 인스턴스가 동일하게 사용되고 있습니다! 그래서 별개로 동작하는 건 아닙니다!
다른 원인을 찾은 것 같은데, 해결을 시도해보고 다시 진행상황 공유해볼게요!!!
